export const add = (a: number, b: number) => a + b;
export const subtract = (a: number, b: number) => a - b;
export const multiply = (a: number, b: number) => a * b;
export const divide = (a: number, b: number) => a / b;
export const power = (a: number, b: number) => a ** b;
export const sqrt = (a: number) => Math.sqrt(a);
export const cbrt = (a: number) => Math.cbrt(a);
export const abs = (a: number) => Math.abs(a);
export const sin = (a: number) => Math.sin(a);
export const cos = (a: number) => Math.cos(a);